services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw,cached
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=dev
    ports:
      - "8081:81"
    depends_on:
      - db
  db:
    environment:
      MYSQL_DATABASE: prompt-writing-db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3308"
volumes:
  db_data:
networks:
  symfony-network:
    driver: bridge