services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw,cached
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=dev
    ports:
      - "8080:80"
    depends_on:
      - db

  # Symfony overrides
  symfony:
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  # MariaDB overrides
  db:
    environment:
      MYSQL_DATABASE: prompt-writing-db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
networks:
  symfony-network:
    driver: bridge