# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  App\Repository\CategoryRepository:
    class: App\Repository\CategoryRepository
    tags: [ 'app.repository']
  App\Repository\FolderRepository:
    class: App\Repository\FolderRepository
    tags: [ 'app.repository']
  App\Repository\NoteRepository:
    class: App\Repository\NoteRepository
    tags: [ 'app.repository']
  App\Repository\PromptRepository:
    class: App\Repository\PromptRepository
    tags: [ 'app.repository']
  App\Repository\TagRepository:
    class: App\Repository\TagRepository
    tags: ['app.repository']
  # this solution is a gist from github (app.doctrine.repository.factory and the one after that)
  # Link: https://gist.github.com/docteurklein/9778800
  app.doctrine.repository.creator:
    class: App\Doctrine\Repository\Factory\RepositoryCreator
    autowire: false
    arguments:
      - $ids:
          - App\Entity\Category: 'App\Repository\CategoryRepository'
          - App\Entity\Folder: 'App\Repository\FolderRepository'
          - App\Entity\Note: 'App\Repository\NoteRepository'
          - App\Entity\Prompt: 'App\Repository\PromptRepository'
          - App\Entity\Tag: 'App\Repository\TagRepository'
      - '@service_container'
      - '@app.doctrine.repository.factory.repository.creator'

    # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones



