# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # this solution is a gist from github (app.doctrine.repository.factory and the one after that)
  # Link: https://gist.github.com/docteurklein/9778800
  app.doctrine.repository.factory:
    class: App\Doctrine\Repository\Factory\RepositoryCreator
    autowire: false
    arguments:
      - [ ]
      - '@service_container'
      - '@app.doctrine.repository.factory.default'
  App\Repository\Factory\IRepository:
      tags: ['app.repository_service']
  app.doctrine.repository.factory.default:
    class: Doctrine\ORM\Repository\DefaultRepositoryFactory
    # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones



